# Generated by Django 3.2.4 on 2021-07-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='TypeAccount',
            field=models.CharField(default='Admin', max_length=54),
        ),
        migrations.AlterField(
            model_name='clients',
            name='TypeAccount',
            field=models.CharField(default='Person Account', max_length=54),
        ),
        migrations.AddField(
            model_name='videos',
            name='categ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
            preserve_default=False,
        ),
    ]
